### ISSUE TITLE
ip/config.yaml template ip capitalization

### ISSUE THREAD

**Issue by flaminggoat** [wulffern/aicex#7]
I think the IP path is missing the capitalization on the `tech_sky130a`, for me at least on Linux it only works if its changed to `tech_sky130A`
https://github.com/wulffern/aicex/blob/b50e0f048427411392f6770842df75e265a9aaf7/ip/config.yaml#L6

Seems to make sense as the repo is named `tech_sky130A`
https://github.com/wulffern/aicex/blob/b50e0f048427411392f6770842df75e265a9aaf7/ip/config.yaml#L63

**Comment by wulffern** [comment]
Absolutely. Thank you. Fixed in 4a07ac6 . 

I don't see this issues on my Mac, since my file system is currently case-insensitive
